runtime: nodejs22
service: pokedex

handlers:
  - url: /(.*\.(js|css|png|jpg|gif|svg|json|ico))
    static_files: dist/pokedex/\1
    upload: dist/pokedex/.*\.(js|css|png|jpg|gif|svg|json|ico)
    redirect_http_response_code: 301

  - url: /.*
    static_files: dist/pokedex/index.html
    upload: dist/pokedex/index.html
    redirect_http_response_code: 301

automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 1
  max_instances: 1
